<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Deepgram" Version="3.4.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.ML" Version="3.0.1" />
    <PackageReference Include="Microsoft.ML" Version="3.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
	<PackageReference Include="Hangfire.Core" Version="1.8.*" />
	<PackageReference Include="Hangfire.SqlServer" Version="1.8.*" />
	<PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\ResponseModels\" />
    <Folder Include="Providers\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SamsonActionModel\SamsonActionModel.csproj" />
    <ProjectReference Include="..\SamsonCommon\SamsonCommon.csproj" />
  </ItemGroup>

</Project>
