// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamsonConsoleApp.Context;

#nullable disable

namespace SamsonConsoleApp.Migrations
{
    [DbContext(typeof(SamsonContext))]
    [Migration("20231204164424_removedUserAuthForNow")]
    partial class removedUserAuthForNow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("SamsonConsoleApp.Models.SpotifyUserAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Access_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Expires_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expires_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Refresh_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("spotifyUserAuths");
                });
#pragma warning restore 612, 618
        }
    }
}
