<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="3.0.1" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="3.0.1" />
    <PackageReference Include="Microsoft.ML.TorchSharp" Version="0.21.1" />
    <PackageReference Include="Microsoft.ML.Vision" Version="3.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.3.1" />
    <PackageReference Include="Spectrogram" Version="1.6.1" />
    <PackageReference Include="TorchSharp-cpu" Version="0.101.5" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\SamsonWakeData\TestData\Audio\" />
    <Folder Include="Data\SamsonWakeData\TestData\Spectogram\" />
    <Folder Include="Data\SpotifyNer\" />
  </ItemGroup>
  <ItemGroup Label="SamsonWakeClassification">
    <None Include="SamsonWakeClassification.mlnet">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="SamsonActionClassification">
    <None Include="SamsonActionClassification.mlnet">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>