// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SamsonActionModel
{
    public partial class SpotifyNer
    {
        /// <summary>
        /// model input class for SpotifyNer.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Sentence")]
            public string Sentence { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Label")]
            public string[] Label { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SpotifyNer.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Sentence")]
            public string Sentence { get; set; }

            [ColumnName(@"Label")]
            public uint[] Label { get; set; }

            [ColumnName(@"predicted_label")]
            public string[] Predicted_label { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SpotifyNer.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
