// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamsonLocal.Context;

#nullable disable

namespace SamsonLocal.Migrations
{
    [DbContext(typeof(SamsonContext))]
    [Migration("20231204160204_moreUserStuff")]
    partial class moreUserStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("SamsonLocal.Models.SamsonUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("samsonUsers");
                });

            modelBuilder.Entity("SamsonLocal.Models.SpotifyUserAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Access_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Expires_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expires_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Refresh_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SamsonUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SamsonUser");

                    b.ToTable("spotifyUserAuths");
                });

            modelBuilder.Entity("SamsonLocal.Models.SpotifyUserAuth", b =>
                {
                    b.HasOne("SamsonLocal.Models.SamsonUser", "User")
                        .WithMany()
                        .HasForeignKey("SamsonUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
