//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class SamsonServerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param summary (optional)
     * @return Success
     */
    action(summary: string | undefined): Promise<SamsonAction> {
        let url_ = this.baseUrl + "/api/Action?";
        if (summary === null)
            throw new Error("The parameter 'summary' cannot be null.");
        else if (summary !== undefined)
            url_ += "summary=" + encodeURIComponent("" + summary) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAction(_response);
        });
    }

    protected processAction(response: Response): Promise<SamsonAction> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = SamsonAction.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SamsonAction>(null as any);
    }

    /**
     * @param chatMessage (optional)
     * @return Success
     */
    question(chatMessage: string | undefined): Promise<Answer> {
        let url_ = this.baseUrl + "/api/Question?";
        if (chatMessage === null)
            throw new Error("The parameter 'chatMessage' cannot be null.");
        else if (chatMessage !== undefined)
            url_ += "chatMessage=" + encodeURIComponent("" + chatMessage) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processQuestion(_response);
        });
    }

    protected processQuestion(response: Response): Promise<Answer> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = Answer.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Answer>(null as any);
    }

    /**
     * @param chatMessage (optional)
     * @return Success
     */
    stream(chatMessage: string | undefined): Promise<Answer> {
        let url_ = this.baseUrl + "/api/Question/stream?";
        if (chatMessage === null)
            throw new Error("The parameter 'chatMessage' cannot be null.");
        else if (chatMessage !== undefined)
            url_ += "chatMessage=" + encodeURIComponent("" + chatMessage) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStream(_response);
        });
    }

    protected processStream(response: Response): Promise<Answer> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = Answer.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Answer>(null as any);
    }

    /**
     * @param body (optional)
     * @return Success
     */
    synth(body: Stream | undefined): Promise<PrerecordedTranscription> {
        let url_ = this.baseUrl + "/Speech/synth";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSynth(_response);
        });
    }

    protected processSynth(response: Response): Promise<PrerecordedTranscription> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = PrerecordedTranscription.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PrerecordedTranscription>(null as any);
    }

    /**
     * @return Success
     */
    tts(): Promise<void> {
        let url_ = this.baseUrl + "/Speech/tts";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTts(_response);
        });
    }

    protected processTts(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional)
     * @return Success
     */
    create(body: UserLogin | undefined): Promise<void> {
        let url_ = this.baseUrl + "/Users/create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional)
     * @return Success
     */
    login(body: UserLogin | undefined): Promise<void> {
        let url_ = this.baseUrl + "/Users/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    settings(id: number): Promise<UserSettings> {
        let url_ = this.baseUrl + "/Users/settings/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSettings(_response);
        });
    }

    protected processSettings(response: Response): Promise<UserSettings> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = UserSettings.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSettings>(null as any);
    }

    /**
     * @param body (optional)
     * @return Success
     */
    wake(body: Stream | undefined): Promise<SamsonWake> {
        let url_ = this.baseUrl + "/api/Wake";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "GET",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWake(_response);
        });
    }

    protected processWake(response: Response): Promise<SamsonWake> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = SamsonWake.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SamsonWake>(null as any);
    }
}

export class ActionParameters implements IActionParameters {

    constructor(data?: IActionParameters) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ActionParameters {
        data = typeof data === 'object' ? data : {};
        let result = new ActionParameters();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IActionParameters {
}

export enum Actions {
    _1000 = 1000,
    _1001 = 1001,
    _1002 = 1002,
    _1003 = 1003,
    _1004 = 1004,
    _2999 = 2999,
    _3000 = 3000,
    _3001 = 3001,
    _3002 = 3002,
    _3003 = 3003,
    _3004 = 3004,
    _3999 = 3999,
    _100000 = 100000,
}

export class Alternative implements IAlternative {
    transcript?: string | undefined;
    confidence?: number;
    words?: Words[] | undefined;
    paragraphs?: ParagraphGroup;
    summaries?: Summary[] | undefined;
    entities?: Entity[] | undefined;
    translations?: Translation[] | undefined;

    constructor(data?: IAlternative) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.transcript = _data["transcript"];
            this.confidence = _data["confidence"];
            if (Array.isArray(_data["words"])) {
                this.words = [] as any;
                for (let item of _data["words"])
                    this.words!.push(Words.fromJS(item));
            }
            this.paragraphs = _data["paragraphs"] ? ParagraphGroup.fromJS(_data["paragraphs"]) : <any>undefined;
            if (Array.isArray(_data["summaries"])) {
                this.summaries = [] as any;
                for (let item of _data["summaries"])
                    this.summaries!.push(Summary.fromJS(item));
            }
            if (Array.isArray(_data["entities"])) {
                this.entities = [] as any;
                for (let item of _data["entities"])
                    this.entities!.push(Entity.fromJS(item));
            }
            if (Array.isArray(_data["translations"])) {
                this.translations = [] as any;
                for (let item of _data["translations"])
                    this.translations!.push(Translation.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Alternative {
        data = typeof data === 'object' ? data : {};
        let result = new Alternative();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["transcript"] = this.transcript;
        data["confidence"] = this.confidence;
        if (Array.isArray(this.words)) {
            data["words"] = [];
            for (let item of this.words)
                data["words"].push(item.toJSON());
        }
        data["paragraphs"] = this.paragraphs ? this.paragraphs.toJSON() : <any>undefined;
        if (Array.isArray(this.summaries)) {
            data["summaries"] = [];
            for (let item of this.summaries)
                data["summaries"].push(item.toJSON());
        }
        if (Array.isArray(this.entities)) {
            data["entities"] = [];
            for (let item of this.entities)
                data["entities"].push(item.toJSON());
        }
        if (Array.isArray(this.translations)) {
            data["translations"] = [];
            for (let item of this.translations)
                data["translations"].push(item.toJSON());
        }
        return data;
    }
}

export interface IAlternative {
    transcript?: string | undefined;
    confidence?: number;
    words?: Words[] | undefined;
    paragraphs?: ParagraphGroup;
    summaries?: Summary[] | undefined;
    entities?: Entity[] | undefined;
    translations?: Translation[] | undefined;
}

export class Answer implements IAnswer {
    text?: string | undefined;

    constructor(data?: IAnswer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): Answer {
        data = typeof data === 'object' ? data : {};
        let result = new Answer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        return data;
    }
}

export interface IAnswer {
    text?: string | undefined;
}

export enum Catergories {
    _1000 = 1000,
    _2000 = 2000,
    _3000 = 3000,
    _100000 = 100000,
}

export class Channel implements IChannel {
    search?: Search[] | undefined;
    alternatives?: Alternative[] | undefined;
    detectedLanguage?: string | undefined;

    constructor(data?: IChannel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["search"])) {
                this.search = [] as any;
                for (let item of _data["search"])
                    this.search!.push(Search.fromJS(item));
            }
            if (Array.isArray(_data["alternatives"])) {
                this.alternatives = [] as any;
                for (let item of _data["alternatives"])
                    this.alternatives!.push(Alternative.fromJS(item));
            }
            this.detectedLanguage = _data["detectedLanguage"];
        }
    }

    static fromJS(data: any): Channel {
        data = typeof data === 'object' ? data : {};
        let result = new Channel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.search)) {
            data["search"] = [];
            for (let item of this.search)
                data["search"].push(item.toJSON());
        }
        if (Array.isArray(this.alternatives)) {
            data["alternatives"] = [];
            for (let item of this.alternatives)
                data["alternatives"].push(item.toJSON());
        }
        data["detectedLanguage"] = this.detectedLanguage;
        return data;
    }
}

export interface IChannel {
    search?: Search[] | undefined;
    alternatives?: Alternative[] | undefined;
    detectedLanguage?: string | undefined;
}

export class Entity implements IEntity {
    label?: string | undefined;
    value?: string | undefined;
    startWord?: number;
    endWord?: number;
    confidence?: number;

    constructor(data?: IEntity) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.label = _data["label"];
            this.value = _data["value"];
            this.startWord = _data["startWord"];
            this.endWord = _data["endWord"];
            this.confidence = _data["confidence"];
        }
    }

    static fromJS(data: any): Entity {
        data = typeof data === 'object' ? data : {};
        let result = new Entity();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["label"] = this.label;
        data["value"] = this.value;
        data["startWord"] = this.startWord;
        data["endWord"] = this.endWord;
        data["confidence"] = this.confidence;
        return data;
    }
}

export interface IEntity {
    label?: string | undefined;
    value?: string | undefined;
    startWord?: number;
    endWord?: number;
    confidence?: number;
}

export class Hit implements IHit {
    confidence?: number;
    start?: number;
    end?: number;
    snippet?: string | undefined;

    constructor(data?: IHit) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.confidence = _data["confidence"];
            this.start = _data["start"];
            this.end = _data["end"];
            this.snippet = _data["snippet"];
        }
    }

    static fromJS(data: any): Hit {
        data = typeof data === 'object' ? data : {};
        let result = new Hit();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["confidence"] = this.confidence;
        data["start"] = this.start;
        data["end"] = this.end;
        data["snippet"] = this.snippet;
        return data;
    }
}

export interface IHit {
    confidence?: number;
    start?: number;
    end?: number;
    snippet?: string | undefined;
}

export enum ListenMode {
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export class Paragraph implements IParagraph {
    sentences?: Sentence[] | undefined;
    start?: number;
    end?: number;
    numberOfWords?: number;
    speaker?: string | undefined;

    constructor(data?: IParagraph) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["sentences"])) {
                this.sentences = [] as any;
                for (let item of _data["sentences"])
                    this.sentences!.push(Sentence.fromJS(item));
            }
            this.start = _data["start"];
            this.end = _data["end"];
            this.numberOfWords = _data["numberOfWords"];
            this.speaker = _data["speaker"];
        }
    }

    static fromJS(data: any): Paragraph {
        data = typeof data === 'object' ? data : {};
        let result = new Paragraph();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.sentences)) {
            data["sentences"] = [];
            for (let item of this.sentences)
                data["sentences"].push(item.toJSON());
        }
        data["start"] = this.start;
        data["end"] = this.end;
        data["numberOfWords"] = this.numberOfWords;
        data["speaker"] = this.speaker;
        return data;
    }
}

export interface IParagraph {
    sentences?: Sentence[] | undefined;
    start?: number;
    end?: number;
    numberOfWords?: number;
    speaker?: string | undefined;
}

export class ParagraphGroup implements IParagraphGroup {
    transcript?: string | undefined;
    paragraphs?: Paragraph[] | undefined;

    constructor(data?: IParagraphGroup) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.transcript = _data["transcript"];
            if (Array.isArray(_data["paragraphs"])) {
                this.paragraphs = [] as any;
                for (let item of _data["paragraphs"])
                    this.paragraphs!.push(Paragraph.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ParagraphGroup {
        data = typeof data === 'object' ? data : {};
        let result = new ParagraphGroup();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["transcript"] = this.transcript;
        if (Array.isArray(this.paragraphs)) {
            data["paragraphs"] = [];
            for (let item of this.paragraphs)
                data["paragraphs"].push(item.toJSON());
        }
        return data;
    }
}

export interface IParagraphGroup {
    transcript?: string | undefined;
    paragraphs?: Paragraph[] | undefined;
}

export class PrerecordedTranscription implements IPrerecordedTranscription {
    requestID?: string | undefined;
    metaData?: PrerecordedTranscriptionMetaData;
    results?: PrerecordedTranscriptionResult;

    constructor(data?: IPrerecordedTranscription) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.requestID = _data["requestID"];
            this.metaData = _data["metaData"] ? PrerecordedTranscriptionMetaData.fromJS(_data["metaData"]) : <any>undefined;
            this.results = _data["results"] ? PrerecordedTranscriptionResult.fromJS(_data["results"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PrerecordedTranscription {
        data = typeof data === 'object' ? data : {};
        let result = new PrerecordedTranscription();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["requestID"] = this.requestID;
        data["metaData"] = this.metaData ? this.metaData.toJSON() : <any>undefined;
        data["results"] = this.results ? this.results.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPrerecordedTranscription {
    requestID?: string | undefined;
    metaData?: PrerecordedTranscriptionMetaData;
    results?: PrerecordedTranscriptionResult;
}

export class PrerecordedTranscriptionMetaData implements IPrerecordedTranscriptionMetaData {
    id?: string | undefined;
    transactionKey?: string | undefined;
    shA256?: string | undefined;
    created?: Date;
    duration?: number;
    channels?: number;
    warnings?: Warning[] | undefined;
    tags?: string[] | undefined;

    constructor(data?: IPrerecordedTranscriptionMetaData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.transactionKey = _data["transactionKey"];
            this.shA256 = _data["shA256"];
            this.created = _data["created"] ? new Date(_data["created"].toString()) : <any>undefined;
            this.duration = _data["duration"];
            this.channels = _data["channels"];
            if (Array.isArray(_data["warnings"])) {
                this.warnings = [] as any;
                for (let item of _data["warnings"])
                    this.warnings!.push(Warning.fromJS(item));
            }
            if (Array.isArray(_data["tags"])) {
                this.tags = [] as any;
                for (let item of _data["tags"])
                    this.tags!.push(item);
            }
        }
    }

    static fromJS(data: any): PrerecordedTranscriptionMetaData {
        data = typeof data === 'object' ? data : {};
        let result = new PrerecordedTranscriptionMetaData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["transactionKey"] = this.transactionKey;
        data["shA256"] = this.shA256;
        data["created"] = this.created ? this.created.toISOString() : <any>undefined;
        data["duration"] = this.duration;
        data["channels"] = this.channels;
        if (Array.isArray(this.warnings)) {
            data["warnings"] = [];
            for (let item of this.warnings)
                data["warnings"].push(item.toJSON());
        }
        if (Array.isArray(this.tags)) {
            data["tags"] = [];
            for (let item of this.tags)
                data["tags"].push(item);
        }
        return data;
    }
}

export interface IPrerecordedTranscriptionMetaData {
    id?: string | undefined;
    transactionKey?: string | undefined;
    shA256?: string | undefined;
    created?: Date;
    duration?: number;
    channels?: number;
    warnings?: Warning[] | undefined;
    tags?: string[] | undefined;
}

export class PrerecordedTranscriptionResult implements IPrerecordedTranscriptionResult {
    channels?: Channel[] | undefined;
    utterances?: Utterance[] | undefined;
    summary?: Summary;

    constructor(data?: IPrerecordedTranscriptionResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["channels"])) {
                this.channels = [] as any;
                for (let item of _data["channels"])
                    this.channels!.push(Channel.fromJS(item));
            }
            if (Array.isArray(_data["utterances"])) {
                this.utterances = [] as any;
                for (let item of _data["utterances"])
                    this.utterances!.push(Utterance.fromJS(item));
            }
            this.summary = _data["summary"] ? Summary.fromJS(_data["summary"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PrerecordedTranscriptionResult {
        data = typeof data === 'object' ? data : {};
        let result = new PrerecordedTranscriptionResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.channels)) {
            data["channels"] = [];
            for (let item of this.channels)
                data["channels"].push(item.toJSON());
        }
        if (Array.isArray(this.utterances)) {
            data["utterances"] = [];
            for (let item of this.utterances)
                data["utterances"].push(item.toJSON());
        }
        data["summary"] = this.summary ? this.summary.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPrerecordedTranscriptionResult {
    channels?: Channel[] | undefined;
    utterances?: Utterance[] | undefined;
    summary?: Summary;
}

export class SamsonAction implements ISamsonAction {
    action?: Actions;
    catergory?: Catergories;
    parameters?: ActionParameters;

    constructor(data?: ISamsonAction) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.action = _data["action"];
            this.catergory = _data["catergory"];
            this.parameters = _data["parameters"] ? ActionParameters.fromJS(_data["parameters"]) : <any>undefined;
        }
    }

    static fromJS(data: any): SamsonAction {
        data = typeof data === 'object' ? data : {};
        let result = new SamsonAction();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["action"] = this.action;
        data["catergory"] = this.catergory;
        data["parameters"] = this.parameters ? this.parameters.toJSON() : <any>undefined;
        return data;
    }
}

export interface ISamsonAction {
    action?: Actions;
    catergory?: Catergories;
    parameters?: ActionParameters;
}

export class SamsonWake implements ISamsonWake {
    isWake?: boolean;

    constructor(data?: ISamsonWake) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isWake = _data["isWake"];
        }
    }

    static fromJS(data: any): SamsonWake {
        data = typeof data === 'object' ? data : {};
        let result = new SamsonWake();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isWake"] = this.isWake;
        return data;
    }
}

export interface ISamsonWake {
    isWake?: boolean;
}

export class Search implements ISearch {
    query?: string | undefined;
    hits?: Hit[] | undefined;

    constructor(data?: ISearch) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.query = _data["query"];
            if (Array.isArray(_data["hits"])) {
                this.hits = [] as any;
                for (let item of _data["hits"])
                    this.hits!.push(Hit.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Search {
        data = typeof data === 'object' ? data : {};
        let result = new Search();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["query"] = this.query;
        if (Array.isArray(this.hits)) {
            data["hits"] = [];
            for (let item of this.hits)
                data["hits"].push(item.toJSON());
        }
        return data;
    }
}

export interface ISearch {
    query?: string | undefined;
    hits?: Hit[] | undefined;
}

export class Sentence implements ISentence {
    text?: string | undefined;
    start?: number;
    end?: number;

    constructor(data?: ISentence) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
            this.start = _data["start"];
            this.end = _data["end"];
        }
    }

    static fromJS(data: any): Sentence {
        data = typeof data === 'object' ? data : {};
        let result = new Sentence();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        data["start"] = this.start;
        data["end"] = this.end;
        return data;
    }
}

export interface ISentence {
    text?: string | undefined;
    start?: number;
    end?: number;
}

export class Stream implements IStream {
    readonly canRead?: boolean;
    readonly canWrite?: boolean;
    readonly canSeek?: boolean;
    readonly canTimeout?: boolean;
    readonly length?: number;
    position?: number;
    readTimeout?: number;
    writeTimeout?: number;

    constructor(data?: IStream) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).canRead = _data["canRead"];
            (<any>this).canWrite = _data["canWrite"];
            (<any>this).canSeek = _data["canSeek"];
            (<any>this).canTimeout = _data["canTimeout"];
            (<any>this).length = _data["length"];
            this.position = _data["position"];
            this.readTimeout = _data["readTimeout"];
            this.writeTimeout = _data["writeTimeout"];
        }
    }

    static fromJS(data: any): Stream {
        data = typeof data === 'object' ? data : {};
        let result = new Stream();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["canRead"] = this.canRead;
        data["canWrite"] = this.canWrite;
        data["canSeek"] = this.canSeek;
        data["canTimeout"] = this.canTimeout;
        data["length"] = this.length;
        data["position"] = this.position;
        data["readTimeout"] = this.readTimeout;
        data["writeTimeout"] = this.writeTimeout;
        return data;
    }
}

export interface IStream {
    canRead?: boolean;
    canWrite?: boolean;
    canSeek?: boolean;
    canTimeout?: boolean;
    length?: number;
    position?: number;
    readTimeout?: number;
    writeTimeout?: number;
}

export class Summary implements ISummary {
    textSummary?: string | undefined;
    startWord?: number;
    endWord?: number;
    short?: string | undefined;

    constructor(data?: ISummary) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.textSummary = _data["textSummary"];
            this.startWord = _data["startWord"];
            this.endWord = _data["endWord"];
            this.short = _data["short"];
        }
    }

    static fromJS(data: any): Summary {
        data = typeof data === 'object' ? data : {};
        let result = new Summary();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["textSummary"] = this.textSummary;
        data["startWord"] = this.startWord;
        data["endWord"] = this.endWord;
        data["short"] = this.short;
        return data;
    }
}

export interface ISummary {
    textSummary?: string | undefined;
    startWord?: number;
    endWord?: number;
    short?: string | undefined;
}

export class Translation implements ITranslation {
    translatedTranscript?: string | undefined;
    language?: string | undefined;

    constructor(data?: ITranslation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.translatedTranscript = _data["translatedTranscript"];
            this.language = _data["language"];
        }
    }

    static fromJS(data: any): Translation {
        data = typeof data === 'object' ? data : {};
        let result = new Translation();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["translatedTranscript"] = this.translatedTranscript;
        data["language"] = this.language;
        return data;
    }
}

export interface ITranslation {
    translatedTranscript?: string | undefined;
    language?: string | undefined;
}

export class UserLogin implements IUserLogin {
    email?: string | undefined;
    password?: string | undefined;
    username?: string | undefined;

    constructor(data?: IUserLogin) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
            this.password = _data["password"];
            this.username = _data["username"];
        }
    }

    static fromJS(data: any): UserLogin {
        data = typeof data === 'object' ? data : {};
        let result = new UserLogin();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["password"] = this.password;
        data["username"] = this.username;
        return data;
    }
}

export interface IUserLogin {
    email?: string | undefined;
    password?: string | undefined;
    username?: string | undefined;
}

export class UserSettings implements IUserSettings {
    id?: number;
    listenMode?: ListenMode;
    listenDuration?: number;

    constructor(data?: IUserSettings) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.listenMode = _data["listenMode"];
            this.listenDuration = _data["listenDuration"];
        }
    }

    static fromJS(data: any): UserSettings {
        data = typeof data === 'object' ? data : {};
        let result = new UserSettings();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["listenMode"] = this.listenMode;
        data["listenDuration"] = this.listenDuration;
        return data;
    }
}

export interface IUserSettings {
    id?: number;
    listenMode?: ListenMode;
    listenDuration?: number;
}

export class Utterance implements IUtterance {
    start?: number;
    end?: number;
    confidence?: number;
    channel?: number;
    transcript?: string | undefined;
    speaker?: number | undefined;
    id?: string | undefined;
    words?: Words[] | undefined;

    constructor(data?: IUtterance) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.start = _data["start"];
            this.end = _data["end"];
            this.confidence = _data["confidence"];
            this.channel = _data["channel"];
            this.transcript = _data["transcript"];
            this.speaker = _data["speaker"];
            this.id = _data["id"];
            if (Array.isArray(_data["words"])) {
                this.words = [] as any;
                for (let item of _data["words"])
                    this.words!.push(Words.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Utterance {
        data = typeof data === 'object' ? data : {};
        let result = new Utterance();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["start"] = this.start;
        data["end"] = this.end;
        data["confidence"] = this.confidence;
        data["channel"] = this.channel;
        data["transcript"] = this.transcript;
        data["speaker"] = this.speaker;
        data["id"] = this.id;
        if (Array.isArray(this.words)) {
            data["words"] = [];
            for (let item of this.words)
                data["words"].push(item.toJSON());
        }
        return data;
    }
}

export interface IUtterance {
    start?: number;
    end?: number;
    confidence?: number;
    channel?: number;
    transcript?: string | undefined;
    speaker?: number | undefined;
    id?: string | undefined;
    words?: Words[] | undefined;
}

export class Warning implements IWarning {
    parameter?: string | undefined;
    type?: WarningType;
    message?: string | undefined;

    constructor(data?: IWarning) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.parameter = _data["parameter"];
            this.type = _data["type"];
            this.message = _data["message"];
        }
    }

    static fromJS(data: any): Warning {
        data = typeof data === 'object' ? data : {};
        let result = new Warning();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["parameter"] = this.parameter;
        data["type"] = this.type;
        data["message"] = this.message;
        return data;
    }
}

export interface IWarning {
    parameter?: string | undefined;
    type?: WarningType;
    message?: string | undefined;
}

export enum WarningType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export class Words implements IWords {
    word?: string | undefined;
    start?: number;
    end?: number;
    confidence?: number;
    punctuatedWord?: string | undefined;
    speaker?: number | undefined;
    speakerConfidence?: number;

    constructor(data?: IWords) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.word = _data["word"];
            this.start = _data["start"];
            this.end = _data["end"];
            this.confidence = _data["confidence"];
            this.punctuatedWord = _data["punctuatedWord"];
            this.speaker = _data["speaker"];
            this.speakerConfidence = _data["speakerConfidence"];
        }
    }

    static fromJS(data: any): Words {
        data = typeof data === 'object' ? data : {};
        let result = new Words();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["word"] = this.word;
        data["start"] = this.start;
        data["end"] = this.end;
        data["confidence"] = this.confidence;
        data["punctuatedWord"] = this.punctuatedWord;
        data["speaker"] = this.speaker;
        data["speakerConfidence"] = this.speakerConfidence;
        return data;
    }
}

export interface IWords {
    word?: string | undefined;
    start?: number;
    end?: number;
    confidence?: number;
    punctuatedWord?: string | undefined;
    speaker?: number | undefined;
    speakerConfidence?: number;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}